#!/usr/bin/env bash

# Make a copy of .bashrc if file exists
if [ -f $HOME/.bashrc ]; then
    cp -v $HOME/.bashrc{,.bak}
fi

echo "[ -f ~/.dotfiles/bashrc ] && . ~/.dotfiles/bashrc" >> $HOME/.bashrc

# Make a copy of .gitconfig if file exists
if [ -f $HOME/.gitconfig ]; then
    mv -v $HOME/.gitconfig{,.bak}
fi

ln -sv $HOME/.dotfiles/gitconfig $HOME/.gitconfig