#!/usr/bin/env bash

# -------------------------------
# asdf
# -------------------------------

# Install asdf
if [ ! -d $HOME/.asdf ]; then
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
fi

# Enable asdf
[ -f ~/.asdf/asdf.sh ] && source ~/.asdf/asdf.sh

# Install asdf plugins
asdf plugin-add nodejs
asdf plugin-add java
asdf plugin-add dart
asdf plugin-add golang

# Install asdf nodejs plugin dependencies
asdf install nodejs $(asdf nodejs resolve lts --latest-available)
asdf global nodejs $(asdf nodejs resolve lts --latest-available)

# Install asdf java plugin dependencies
asdf install java latest:temurin-21
asdf global java latest:temurin-21

# Install asdf dart plugin dependencies
asdf install dart latest
asdf global dart latest

# Install asdf golang plugin dependencies
asdf install golang latest
asdf global golang latest

# -------------------------------
# Bash
# -------------------------------

# Add dotfiles to bashrc
if ! grep -q "source ~/.dotfiles/shell/bashrc" ~/.bashrc; then
    echo -e "\n[ -f ~/.dotfiles/shell/bashrc ] && source ~/.dotfiles/shell/bashrc" >> ~/.bashrc
fi

# If ~/.bashrc does not exist, create it
if [ ! -f ~/.bashrc ]; then
    touch ~/.bashrc
fi

# if running bash, load .bashrc
if [ -n "$BASH_VERSION" ]; then
    [ -f ~/.bashrc ] && source ~/.bashrc
fi

# -------------------------------
# Zsh
# -------------------------------

# Install zsh
if ! command -v zsh &> /dev/null; then
    sudo apt install -y zsh
fi

# If ~/.zshrc does not exist, create it
if [ ! -f ~/.zshrc ]; then
    touch ~/.zshrc
fi

# Add dotfiles to zshrc
if ! grep -q "source ~/.dotfiles/shell/zshrc" ~/.zshrc; then
    echo -e "\n[ -f ~/.dotfiles/shell/zshrc ] && source ~/.dotfiles/shell/zshrc" >> ~/.zshrc
fi

# if running zsh, load .zshrc
if [ -n "$ZSH_VERSION" ]; then
    [ -f ~/.zshrc ] && source ~/.zshrc
fi

# -------------------------------
# Git
# -------------------------------

# Install git
if ! command -v git &> /dev/null; then
    sudo apt install -y git
fi

# Add gitconfig
if [ ! -f ~/.gitconfig ]; then
    cp ~/.dotfiles/gitconfig ~/.gitconfig
fi

# -------------------------------
# Vim
# -------------------------------

# Install vim
if ! command -v vim &> /dev/null; then
    sudo apt install -y vim
fi

# Add vimrc
if [ ! -f ~/.vimrc ]; then
    cp ~/.dotfiles/vimrc ~/.vimrc
fi